apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
    app: demo

spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis
      app: demo
  template:
    metadata:
      labels:
        name: redis
        app: demo
    
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379         
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-pv-claim
